opensea:
  asset_owner: "0x9c847ce765a48701fba267366eefa12606780d72"
  collection: "monsters-evolution"

twitter:
  path_to_secrets: '../../../secrets.yaml'
  hashtags: "#nfts #nft #nftart #nftartist #nftcollector #cryptoart #digitalart #nftcommunity #art #crypto #ethereum #blockchain #cryptocurrency #cryptoartist #opensea #nftcollectors"