opensea:
  asset_owner: "0x9c847ce765a48701fba267366eefa12606780d72"
  collection: "monsters-evolution"

twitter:
  api_key: null
  api_secret: null
  access_token: null
  access_token_secret: null
  hashtags: "#nfts #nft #nftart #nftartist #nftcollector #cryptoart #digitalart #nftcommunity #art #crypto #ethereum #blockchain #cryptocurrency #cryptoartist #opensea #nftcollectors"