# This is a basic workflow to help you get started with Actions

name: NFT Replying

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9.7'
      # Runs a single command using the runners shell
      - name: Install Requirements
        run: pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: Reply to Tweets
        run: python src/find_nft_buyers.py -m twitter.api_key=${{ secrets.API_KEY }} twitter.api_secret=${{ secrets.API_SECRET }} twitter.access_token=${{ secrets.ACCESS_TOKEN }} twitter.access_token_secret=${{ secrets.ACCESS_TOKEN_SECRET }}
